Use correct source database identifier
On applying this Terraform, the following error was returned:

```
Error: creating RDS DB Instance (read replica)
(integration-publishing-api-postgres-replica): operation error RDS:
CreateDBInstanceReadReplica, https response error StatusCode: 400,
RequestID: fb6ddccd-40fa-4d71-ad8b-aab147c03499, api error
InvalidParameterValue: The parameter SourceDBInstanceIdentifier is not a
valid identifier. Identifiers must begin with a letter; must contain
only ASCII letters, digits, and hyphens; and must not end with a hyphen
or contain two consecutive hyphens.
```

Updating to use the actual identifier, not a plain string.