Update govuk-knowledge-graph-search pull_request_bypassers
The username appears to have changed and is now causing TF errors

Error: Could not resolve to a User with the login of 'guilhem-fry'.
with github_branch_protection.govuk_repos[govuk-knowledge-graph-search]
on main.tf line 143, in resource github_branch_protection govuk_repos