Add aws_cloudwatch_event_rule for chat in eu-west-2
We had a few apply actions fail for creating cloudwatch alarams. These
have now been resolved. However, we've got 1 final issue with our Apply
which is:

```
ResourceNotFoundException: Rule chat-aws-service-health-alert does not
exist on EventBus default
```

This is happening because the rule exists in eu-west-1 but not in eu-west-2.
This commit adds the rule to eu-west-2 and should resolve the issue.